# Generated by Django 4.1.7 on 2023-11-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_fizuser_options_alter_uruser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fizuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='uruser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
